apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
#  namespace: gateway-tier
spec:
  replicas: 1
  selector:
    matchLabels:
      name: gateway
  template:
    metadata:
      labels:
        name: gateway
    spec:
      #nodeName: worker2
      containers:
      - name: gateway
        image: egapm/docker-compose-kubernetes:gateway
        ports:
        - containerPort: 8080
---
#apiVersion: v1
#kind: Service
#metadata:
#  name: mastercardpaymentgateway 
#spec:
#  selector:
#    name: gateway 
#  ports:
#  - port: 80
#    targetPort: 80
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: visapaymentgateway 
#spec:
#  selector:
#    name: gateway 
#  ports:
#  - port: 80
#    targetPort: 80
#---
apiVersion: v1
kind: Service
metadata:
  name: gateway 
spec:
  selector:
    name: gateway 
  ports:
  - port: 80
    targetPort: 80
