apiVersion: apps/v1
kind: Deployment
metadata:
  name: quote
#  namespace: quote-tier
spec:
  replicas: 1
  selector:
    matchLabels:
      name: quote
  template:
    metadata:
      labels:
        name: quote
    spec:
      #nodeName: worker2
      containers:
      - name: quote
        image: egapm/docker-compose-kubernetes:quote
        ports:
        - containerPort: 8080
        volumeMounts:
         - name: config-vol
           mountPath: /opt/egbtm
        env:
         - name: JAVA_OPTS  #-javaagent:/opt/egbtm/eg_btm.jar 
           value: "-Duser.timezone=Asia/Singapore -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.port=3333 -Dcom.sun.management.jmxremote.rmi.port=3333 -DeG_Service_Name=Webstore-microsvc -DeG_Group_Name=Quote"
      volumes:
      - name: config-vol
        hostPath:
         path: /opt/egurkha/lib/apm/Java/default 
         type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: quote
spec:
  selector:
    name: quote 
  ports:
  - port: 80
    targetPort: 8080
